### ISSUE TITLE
next ?

### ISSUE THREAD

**Issue by PManager1** [rafasantos/twilio-sms-web#3]
Hi great app. Any plans of new versions of this application ?

**Comment by rafacandev** [comment]
There is a number of people using this app. Mostly QA people testing features like 2FA or SMS reminders. They are very happy with the app from what I can tell.

The most requested feature is real time updates for the messages list. But I will need to explore Twilio's offerings to see if we can do it without pooling (because I dislike this approach) and without using webhooks (because this app doesn't have a backend).

I'm also exploring the ability to manage contacts but I am not sure if people is going to use this feature because most QA people receive SMS messages from a pool of phone number in a round robin fashion; so, it might not be super useful for them.


@jpca999 Do you have anything specific in mind?

**Comment by PManager1** [comment]
I have explored other apps in this category and I can tell most of them are horrible.

I believe if you can provide following options that would be great!

1. Some way to tell the user that these are the new messages received since you last opened the app, just like our phone texts. 

2. I believe you can make the texting to the number easier, right now you have to copy the number and open it in another tab. 

3. Ability to make & receive phone calls.  User can’t make calls from Twilio number. 

4. Send notifications to real phone. Right now it charges extra for message forwarding to receive notifications.

**Comment by uhgupdate** [comment]
sir how to deploy this app on cpanel

**Comment by rafacandev** [comment]
Hi @jpca999 , thank you very much for the suggestions I truly appreciate it.

> 1. Some way to tell the user that these are the new messages received since you last opened the app, just like our phone texts.

Very good idea. My intent for this app is to be a pure javascript/frontend app without any backend or database other than Twilio. I would like to keep dependencies at a minimum so it is easy for others to deploy and use it anywhere they want. That being said, I am going to see if I can do that with Twilio services. I will get back to you later.

> 2. I believe you can make the texting to the number easier, right now you have to copy the number and open it in another tab.

That's an excellent, I am going to work on this possibly next month.

> 3. Ability to make & receive phone calls.  User can’t make calls from Twilio number.

That's an intriguing request. People I know who uses this app only need to send and receive SMS mainly for testing 2FA or scheduler appointments via SMS. I will do some basic research to evaluate how much work that would be. By the way, may I know what is your use case if you don't mind sharing (no problem if you prefer not to share)? Additionally, receiving phone calls might be a challenge, I will take a look though.

> 4. Send notifications to real phone. Right now it charges extra for message forwarding to receive notifications.

Something like routing the message to a different phone number, right? Maybe, we could fire a webhook so you could read the message in a different backend or send a message to another phone. Additionally, we could drop the incoming message from Twilio in the hopes to save costs. But I don't think this approach is going to reduce any cost or even worse, it might increase costs. At any rate, Twilio offers something called [TWiML](https://www.twilio.com/docs/voice/twiml) that you can customize directly without making changes to this app. Take a look and let me know your thoughts.

**Comment by rafacandev** [comment]
> [uhgupdate](/uhgupdate)

Hi, I created another issue to separate the subject. Please, let's continue the conversation in there: https://github.com/rafasantos/twilio-sms-web/issues/4
